# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-07 13:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_auto_20160329_1259'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='blog',
            table='blog_posts',
        ),
    ]
