# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-27 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('link', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=128)),
                ('thumbnail_filename', models.CharField(max_length=128)),
            ],
        ),
    ]
