# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='subtitle',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
