# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-07 13:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sites', '0002_site_precedence'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='site',
            table='sites',
        ),
    ]
