# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sites', '0003_auto_20160607_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='online',
            field=models.BooleanField(default=False),
        ),
    ]
