# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 12:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sites', '0004_site_online'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='precedence',
        ),
    ]
